const activities = [
  // Fun activities to do when stuck inside
  "Play an instrument",
  "Write a short story",
  "Do a deep dive on a subject that interests you",
  "Fill out a crossword puzzle",
  "Try Origami",
  "Play a board game",
  "Put together a puzzle",
  "Watch a rom-com marathon",
  "Sing along to some Disney songs",
  "Plan your next getaway",
  "Build a fort",
  "Try new outfits",
  "Write a letter",
  "Watch a sports game",
  "Call a friend",
  "Watch a performance",
  "Learn a new language",
  "Watch a solo movie",
  "Have a dance party",
  "Learn some popular moves",
  "Play a video game",
  // Creative things to do indoors
  "Tie-dye an outfit",
  "Paint a picture",
  "Start scrapbooking",
  "Make pottery",
  "Make jewelry that matches your style",
  "Learn a how to do new hairstyle",
  "Start a new book",
  "Download an audiobook",
  "Listen to a new podcast",
  "Try a coloring app",
  "Make a custom photo book",
  "Change up your décor",
  "Make some wall art",
  "Whip up a new recipe",
  "Craft a complex meal",
  "Bake cookies",
  "Learn cake decorating",
  "Make homemade ice cream",
  "Indulge in a sundae bar",
  "Eat breakfast for dinner",
  "Build a gingerbread house",
  "Work on your wish list",
  "Become a YouTube or TikTok star",
  "Put together a care package",
  "Write to a deployed soldier",
  // Relaxing stress - relief activities
  "Make a gratitude list",
  "Write out your goals",
  "Unplug your devices",
  "Do a random act of kindness",
  "Give knitting a try",
  "Paint your nails",
  "Take a bubble bath",
  "Put on a face mask",
  "Give your sweetie a massage",
  "Start journaling",
  "Listen to a meditation video",
  "Try living room yoga",
  "Do Zumba",
  "Work your core",
  "Try a new exercise routine",
  "Give a pep talk",
  "Have a lights-out night",
  "Walk down memory lane",
  "Sleep somewhere new",
  "Vent your frustrations",
  // Organizing activities to pass time
  "Straighten up your junk drawer",
  "Move your furniture around",
  "Move some art",
  "Meal prep for the week",
  "Clean out your attic",
  "Clean your dishwasher",
  "Wash your washing machine",
  "Scour your whole house",
  "Shine the windows",
  "Clean your pillows",
  "Wash your makeup brushes",
  "Sort through your purses",
  "Clean out your closet",
  "Organize your kitchen",
  "Refresh your mantel",
  "Spruce up your outdoor space",
  "Spot-treat your white shoes",
  "Shop for new essentials",
  "Give an old piece new life",
  "Tackle a trouble spot",
  // Outdoor activities to do when you're bored
  "Head outside",
  "Get lost in your hometown",
  "Set up a blanket and go stargazing",
  "Go for a jog",
  "Light a campfire",
  "Watch a movie outdoors",
  "Dine al fresco",
  "Go for a long walk",
  "Take your pet to the park",
  "Start a garden",
  "Go for a bike ride",
  "Take a drive",
  "Hit the beach",
  "Have a backyard camp out",
  "Go for a hike",

]

export default activities;